# A list of container types that can be classified as shops
container-whitelist:
  - "minecraft:chest"
  - "minecraft:trapped_chest"
  - "minecraft:barrel"

# A list of sign types that can be used for container shops
sign-whitelist:
  - "#signs"
  - "#all_hanging_signs"

# If enabled, sign shops will display a packet based item visual above the shop
# Note: This visual will appear below hanging sign shops
display-visual: true

# If enabled, only containers directly connected to a sign can be classified as a shop
# If disabled, containers above/below the directly connected block can be checked too
# Note: Only the first container found will be classified as a shop)
connected-containers-only: true

# Whether the following attributes should be compared when comparing products and costs
should-compare:
  display-names: true
  custom-model-data: true

messages:
  updated-shop: "&#b7faa2Successfully updated your shop"
  not-shop: "&#ff6969You must be looking at a shop to run this command"
  cannot-edit: "&#ff6969You do not own this shop"
  bypassed-protection: "&#ffda54You have bypassed a locked shop container"
  no-access: "&#ff6969This container is a locked shop container"
  no-container: "&#ff6969This shop is not connected to a container"
  not-setup: "&#ff6969This shop is not ready to purchase from yet"
  no-item: "&#ff6969You must be holding an item to set the shop's product or cost"
  wrong-side: "&#ff6969Shops can only be created on the side that was facing you when you placed the sign"
  reload: "&#b7faa2LushContainerShops has been reloaded &#66b04fðŸ”ƒ"
  # Colour of the top line of sign shops
  header-color: "&#FFC56F"
  # Statuses for the bottom line of sign shops
  in-stock-status: "&#BFF6A9In Stock"
  out-of-stock-status: "&#FDE480Out of Stock"
  not-setup-status: "&cInvalid Shop"